name: fallout-savegame

dependencies:
    - base
    - filepath
    - bytestring
    - cereal
    - time
    - microlens-platform
    - template-haskell
    - brick
    - vty
    - QuickCheck
    - quickcheck-instances

library:
    source-dirs:
        - src
    exposed-modules:
        - Timestamp
        - FixedLengthCString
        - ReadSave

executables:
    interactive:
        source-dirs:
            - exe
        main: Form
        dependencies:
            - fallout-savegame
        ghc-options:
            - -threaded

tests:
    test:
        source-dirs:
            - test
        main: Test
        dependencies:
            - fallout-savegame
            - tasty
            - tasty-quickcheck
            - tasty-hunit
            - tasty-golden
            - props
