dependencies:
    - base
    - filepath
    - bytestring
    - cereal
    - time
    - microlens-platform
    - template-haskell
    - brick
    - vty
    - QuickCheck
    - quickcheck-instances

executables:
    interactive:
        main: Form
        ghc-options:
            - -threaded

tests:
    test:
        main: Test
        dependencies:
            - tasty
            - tasty-quickcheck
            - tasty-hunit
            - tasty-golden
            - props
