dependencies:
    - base
    - filepath
    - bytestring
    - cereal
    - time
    - microlens-platform
    - template-haskell
    - brick
    - vty
    - QuickCheck
    - quickcheck-instances

library:
    exposed-modules:
        - Timestamp
        - FixedLengthCString
        - ReadSave

executables:
    interactive:
        source-dirs:
            - exe
        main: Form
        dependencies:
            - Fallout
        ghc-options:
            - -threaded

tests:
    test:
        source-dirs:
            - test
        main: Test
        dependencies:
            - Fallout
            - tasty
            - tasty-quickcheck
            - tasty-hunit
            - tasty-golden
            - props
